create table if not exists public.task_reminder_deliveries (
  id bigint generated by default as identity primary key,
  task_id text not null,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  reminder_date date not null,
  reminder_time time not null,
  sent_at timestamptz not null default now(),
  unique(task_id, recipient_id, reminder_date, reminder_time)
);
alter table public.task_reminder_deliveries enable row level security;
create index if not exists task_reminder_deliveries_lookup_idx on public.task_reminder_deliveries(task_id, reminder_date);
revoke all on public.task_reminder_deliveries from anon, authenticated;
