-- Checklist v8.50: notificações persistentes de tarefas compartilhadas.
-- Pode ser executado mais de uma vez no SQL Editor do Supabase.

create table if not exists public.shared_task_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  task_id text not null,
  task_title text not null,
  category_name text,
  assigned_to text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.shared_task_notifications enable row level security;

create index if not exists shared_task_notifications_recipient_idx
on public.shared_task_notifications(recipient_id, created_at desc);

drop policy if exists "Recipients read shared task notifications"
on public.shared_task_notifications;
create policy "Recipients read shared task notifications"
on public.shared_task_notifications
for select to authenticated
using (recipient_id = auth.uid());

drop policy if exists "Recipients update shared task notifications"
on public.shared_task_notifications;
create policy "Recipients update shared task notifications"
on public.shared_task_notifications
for update to authenticated
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());

create or replace function public.notify_shared_task_created()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.category_id is null then
    return new;
  end if;

  -- Avisa o proprietário quando a tarefa foi criada pelo colaborador.
  insert into public.shared_task_notifications
    (recipient_id, actor_id, task_id, task_title, category_name, assigned_to)
  select c.user_id, new.user_id, new.id::text, new.title, c.name, new.assigned_to
  from public.categories c
  where c.id = new.category_id
    and c.user_id <> new.user_id;

  -- Avisa cada colaborador aceito, exceto quem criou a tarefa.
  insert into public.shared_task_notifications
    (recipient_id, actor_id, task_id, task_title, category_name, assigned_to)
  select distinct u.id, new.user_id, new.id::text, new.title, c.name, new.assigned_to
  from public.categories c
  join public.category_shares cs
    on cs.category_id = c.id
   and cs.accepted is true
  join auth.users u
    on lower(trim(u.email)) = lower(trim(cs.collaborator_email))
  where c.id = new.category_id
    and u.id <> new.user_id;

  return new;
end;
$$;

drop trigger if exists tasks_notify_shared_creation on public.tasks;
create trigger tasks_notify_shared_creation
after insert on public.tasks
for each row execute function public.notify_shared_task_created();

do $$
begin
  alter publication supabase_realtime add table public.shared_task_notifications;
exception
  when duplicate_object then null;
end $$;
