-- Checklist v8.32: colaboração segura por categoria e convites em tempo real.
-- Execute uma vez no SQL Editor do projeto Supabase.

alter table public.tasks
add column if not exists category_id bigint references public.categories(id) on delete cascade;

alter table public.category_shares
add column if not exists accepted boolean not null default false;

-- Compatibilidade com tarefas antigas: relaciona pelo proprietário + nome.
update public.tasks t
set category_id = c.id
from public.categories c
where t.category_id is null
  and t.user_id = c.user_id
  and lower(trim(t.category)) = lower(trim(c.name));

-- Recupera também tarefas antigas criadas pelo colaborador dentro da categoria do proprietário.
update public.tasks t
set category_id = c.id
from public.categories c
join public.category_shares cs on cs.category_id = c.id and cs.accepted is true
join auth.users u on lower(trim(u.email)) = lower(trim(cs.collaborator_email))
where t.category_id is null
  and t.user_id = u.id
  and lower(trim(t.category)) = lower(trim(c.name));

create index if not exists tasks_category_id_idx on public.tasks(category_id);
create index if not exists category_shares_category_id_idx on public.category_shares(category_id);
create index if not exists category_shares_collaborator_email_idx
on public.category_shares(lower(trim(collaborator_email)));

alter table public.categories enable row level security;
alter table public.tasks enable row level security;
alter table public.completions enable row level security;
alter table public.category_shares enable row level security;

create table if not exists public.shared_task_notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  task_id text not null,
  task_title text not null,
  category_name text,
  assigned_to text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.shared_task_notifications enable row level security;
create index if not exists shared_task_notifications_recipient_idx
on public.shared_task_notifications(recipient_id, created_at desc);

drop policy if exists "Recipients read shared task notifications" on public.shared_task_notifications;
create policy "Recipients read shared task notifications"
on public.shared_task_notifications for select
using (recipient_id = auth.uid());

drop policy if exists "Recipients update shared task notifications" on public.shared_task_notifications;
create policy "Recipients update shared task notifications"
on public.shared_task_notifications for update
using (recipient_id = auth.uid())
with check (recipient_id = auth.uid());

create or replace function public.notify_shared_task_created()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if new.category_id is null then
    return new;
  end if;

  -- Notifica o proprietário quando outra pessoa cria a tarefa.
  insert into public.shared_task_notifications
    (recipient_id, actor_id, task_id, task_title, category_name, assigned_to)
  select c.user_id, new.user_id, new.id::text, new.title, c.name, new.assigned_to
  from public.categories c
  where c.id = new.category_id
    and c.user_id <> new.user_id;

  -- Notifica colaboradores aceitos, exceto quem criou a tarefa.
  insert into public.shared_task_notifications
    (recipient_id, actor_id, task_id, task_title, category_name, assigned_to)
  select distinct u.id, new.user_id, new.id::text, new.title, c.name, new.assigned_to
  from public.categories c
  join public.category_shares cs on cs.category_id = c.id and cs.accepted is true
  join auth.users u on lower(trim(u.email)) = lower(trim(cs.collaborator_email))
  where c.id = new.category_id
    and u.id <> new.user_id;

  return new;
end;
$$;

drop trigger if exists tasks_notify_shared_creation on public.tasks;
create trigger tasks_notify_shared_creation
after insert on public.tasks
for each row execute function public.notify_shared_task_created();

drop policy if exists "Collaboration can read categories" on public.categories;
create policy "Collaboration can read categories"
on public.categories for select
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.category_shares cs
    where cs.category_id = categories.id
      and lower(trim(cs.collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
  )
);

drop policy if exists "Owners manage categories" on public.categories;
create policy "Owners manage categories"
on public.categories for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "Participants can read category shares" on public.category_shares;
create policy "Participants can read category shares"
on public.category_shares for select
using (
  owner_id = auth.uid()
  or lower(trim(collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
);

drop policy if exists "Owners create category shares" on public.category_shares;
create policy "Owners create category shares"
on public.category_shares for insert
with check (owner_id = auth.uid());

drop policy if exists "Invitees accept category shares" on public.category_shares;
create policy "Invitees accept category shares"
on public.category_shares for update
using (lower(trim(collaborator_email)) = lower(trim(auth.jwt() ->> 'email')))
with check (lower(trim(collaborator_email)) = lower(trim(auth.jwt() ->> 'email')));

drop policy if exists "Participants delete category shares" on public.category_shares;
create policy "Participants delete category shares"
on public.category_shares for delete
using (
  owner_id = auth.uid()
  or lower(trim(collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
);

drop policy if exists "Collaboration can read tasks" on public.tasks;
create policy "Collaboration can read tasks"
on public.tasks for select
using (
  user_id = auth.uid()
  or exists (select 1 from public.categories c where c.id = tasks.category_id and c.user_id = auth.uid())
  or exists (
    select 1 from public.category_shares cs
    where cs.category_id = tasks.category_id
      and cs.accepted is true
      and lower(trim(cs.collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
  )
  or exists (
    select 1 from public.categories c
    join public.category_shares cs on cs.category_id = c.id
    where c.id = tasks.category_id
      and cs.accepted is true
      and cs.owner_id = auth.uid()
  )
);

drop policy if exists "Participants create tasks" on public.tasks;
create policy "Participants create tasks"
on public.tasks for insert
with check (
  user_id = auth.uid()
  and (
    category_id is null
    or exists (select 1 from public.categories c where c.id = category_id and c.user_id = auth.uid())
    or exists (
      select 1 from public.category_shares cs
      where cs.category_id = tasks.category_id
        and cs.accepted is true
        and lower(trim(cs.collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
    )
  )
);

drop policy if exists "Participants update tasks" on public.tasks;
create policy "Participants update tasks"
on public.tasks for update
using (
  user_id = auth.uid()
  or exists (select 1 from public.categories c where c.id = tasks.category_id and c.user_id = auth.uid())
  or exists (
    select 1 from public.category_shares cs
    where cs.category_id = tasks.category_id
      and cs.accepted is true
      and lower(trim(cs.collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
  )
)
with check (
  user_id = auth.uid()
  or exists (select 1 from public.categories c where c.id = tasks.category_id and c.user_id = auth.uid())
  or exists (
    select 1 from public.category_shares cs
    where cs.category_id = tasks.category_id
      and cs.accepted is true
      and lower(trim(cs.collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
  )
);

drop policy if exists "Participants delete tasks" on public.tasks;
create policy "Participants delete tasks"
on public.tasks for delete
using (
  user_id = auth.uid()
  or exists (select 1 from public.categories c where c.id = tasks.category_id and c.user_id = auth.uid())
  or exists (
    select 1 from public.category_shares cs
    where cs.category_id = tasks.category_id
      and cs.accepted is true
      and lower(trim(cs.collaborator_email)) = lower(trim(auth.jwt() ->> 'email'))
  )
);

drop policy if exists "Participants read completions" on public.completions;
create policy "Participants read completions"
on public.completions for select
using (exists (select 1 from public.tasks t where t.id = completions.task_id));

drop policy if exists "Participants create completions" on public.completions;
create policy "Participants create completions"
on public.completions for insert
with check (exists (
  select 1 from public.tasks t
  where t.id = completions.task_id
    and (
      nullif(trim(t.assigned_to), '') is null
      or lower(trim(t.assigned_to)) = lower(trim(auth.jwt() ->> 'email'))
    )
));

drop policy if exists "Participants update completions" on public.completions;
create policy "Participants update completions"
on public.completions for update
using (exists (
  select 1 from public.tasks t
  where t.id = completions.task_id
    and (
      nullif(trim(t.assigned_to), '') is null
      or lower(trim(t.assigned_to)) = lower(trim(auth.jwt() ->> 'email'))
    )
))
with check (exists (
  select 1 from public.tasks t
  where t.id = completions.task_id
    and (
      nullif(trim(t.assigned_to), '') is null
      or lower(trim(t.assigned_to)) = lower(trim(auth.jwt() ->> 'email'))
    )
));

drop policy if exists "Participants delete completions" on public.completions;
create policy "Participants delete completions"
on public.completions for delete
using (exists (
  select 1 from public.tasks t
  where t.id = completions.task_id
    and (
      nullif(trim(t.assigned_to), '') is null
      or lower(trim(t.assigned_to)) = lower(trim(auth.jwt() ->> 'email'))
    )
));

-- Habilita eventos de convite para o sininho sem exigir recarregar a página.
do $$
begin
  alter publication supabase_realtime add table public.category_shares;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.shared_task_notifications;
exception
  when duplicate_object then null;
end $$;
