-- Checklist v10.19: trava de idempotência para as saudações push das 06h e 21h.
-- A Edge Function send-scheduled-reminders usa esta tabela para garantir no
-- máximo uma saudação por usuário, período e dia (horário de Brasília).

create table if not exists public.daily_push_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  delivery_date date not null,
  period text not null check (period in ('morning', 'evening')),
  created_at timestamptz not null default now(),
  unique (user_id, delivery_date, period)
);

alter table public.daily_push_deliveries enable row level security;
create index if not exists daily_push_deliveries_date_idx
  on public.daily_push_deliveries(delivery_date);

-- A tabela é de controle interno e só pode ser acessada pela service role.
revoke all on public.daily_push_deliveries from anon, authenticated;

-- Limpeza inicial. A função também remove registros dos meses anteriores.
delete from public.daily_push_deliveries
where delivery_date < (current_date - interval '45 days');
